### PR TITLE
Message to, fork a formatted code

### PR DESCRIPTION
**Pull request by RMCoder198**
Associated Issue: #162 

Here's the contributing guide at https://github.com/wasdk/WebAssemblyStudio/wiki/Contributing

 Summary of Changes

Whenever user forks a project , user will receive a message to fork a formatted code

Test Plan

Make changes in file

Run localhost 

check the desired changes

run command npm run test

Screenshots/Videos (OPTIONAL)
fork

### CODE REVIEW

**Comment by mbebenita** [comment]
This is a bit tricky from an UX perspective. Really what you want is that whenever someone wants to share something, you want them to be reminded they should format their code. Maybe the easiest thing is to put a warning on the sharing page reminding the user to format their code.

**Comment by RMCoder198** [comment]
@mbebenita 
Only forked code gets  shared , that's why i chose to remind user to format  code when user  forks his/her code.
But if you want to do it in your way , that is good .

**Comment by mbebenita** [comment]
> remind user to format code when user forks his/her code

The issue here is that I think you want to remind them, and prevent them from actually forking if they decide to go back an format it. If you let them fork, and then give them a reminder, then they'll have to go back and fork again after they formatted things.

**Comment by RMCoder198** [comment]
Ok ,i got it.

**Pull request closed without merging**
