### PR TITLE
Add rust syntax

### LINKED ISSUE #49: Rust needs syntax highlighting
The current version doesn't seem to do any highlighting for Rust.  

screen shot 2018-02-10 at 6 20 23 am

### PR DESCRIPTION
**Pull request by MaxGraey**
### Summary of Changes

- [x] Add rust language file for monaco
- [x] Fix missing case for Rust in languageForFileType
- [x] Register new language provider
- [x] Fix wrong ordering bugs of custom provider registration
- [x] Make syntax finally work 

### Done!

Partially resolve #49 and #41 issues

### CODE REVIEW

**Comment by yurydelendik** [comment]
Part of #41

**Comment by yurydelendik** [comment]
> Syntax still not work. Help wanted!

Can you list items to be completed with markdown todo items: `- [ ] item 1`? (See #41 as example)

Few hints: try to avoid "minor fix" commit -- squash such commits, and try not to add unrelated to PR changes (e.g. `=` alignment).

**Comment by yurydelendik** [comment]
> >   Syntax still not work. Help wanted!

> Can you list items to be completed with markdown todo items: - [ ] item 1? 

You did it for summary of change, I asked for "Help wanted!" section.

**Comment by yurydelendik** [comment]
screen shot 2018-02-11 at 9 27 28 am

What do you need help with in this PR?

**Comment by MaxGraey** [comment]
I think something missing. Log clear, any errors is missing, but syntax still not work as expected

**Comment by yurydelendik** [comment]
> I think something missing. Log clear, any errors are missing, but syntax still not work as expected

I see. Can you mention that instead of "Help Wanted"?

**Comment by MaxGraey** [comment]
Sure! Done

**Comment by MaxGraey** [comment]
I found what is problem. Now we can merge

**Comment by mbebenita** [comment]
Thanks! This is great. You may also want to consider submitting a similar patch to https://github.com/Microsoft/monaco-languages so that all users of Monaco get Rust highlighting out of the box.

**Comment by MaxGraey** [comment]
@mbebenita not yet, this very basic implementation which needs in improvements

**Pull request merged**
