### PR TITLE
Support template file with external contents

### PR DESCRIPTION
**Pull request by tschneidereit**
Associated Issue: None

### Summary of Changes

* Add support for loading a template's files on-demand instead of embedding them all into the templates file itself.
* The code that creates the templates file is also changed to copy files over to `dist/templates/[template name]`.
* Same for the code for loading files to properly resolve paths relative to the templates file.

### Test Plan

- [x] Open WebAssembly.studio
- [x] Select a template
- [x] Click the "Create" button
- [x] Open all of the project's files to ensure they're all as expected
- [x] Build and Run project to ensure it works as expected
- [x] Repeat for all templates

### CODE REVIEW

**Comment by tschneidereit** [comment]
@yurydelendik, @mbebenita this is the change I was talking about earlier. It should make it much easier to provide custom templates via an embedding. We probably need to talk about security implications of that before actually making that possible.

**Comment by tschneidereit** [comment]
I'll look into the test failure tomorrow.

**Comment by tschneidereit** [comment]
@ollelauribostrom, @yurydelendik tells me you know a lot about the test infrastructure, so perhaps you can help me with this test failure? `fetch` doesn't just work in tests, so I added a mock for `getConfig`, which is now used by the code under test. However, now I'm running into issues with `URL`. Can you give me a pointer for how to work around those? I don't even need the result of what `URL` is used for here, but refactoring the code to only use `URL` if it's really needed would make it much less clear :(

**Comment by ollelauribostrom** [comment]
@tschneidereit I'll look in to this tonight!

**Comment by tschneidereit** [comment]
@ollelauribostrom, excellent, thank you so much!

**Comment by yurydelendik** [comment]
Thank you for the patch!

**Pull request merged**
